wandb_version: 1

batch_size:
  desc: null
  value: 12
isServer:
  desc: null
  value: true
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713256549.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.7
      5: 0.16.5
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
